name: pusheos

on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          committer: Fabricio Blas <fblas@mobydigital.com>
          fqdn: vinacobos.mobydigital.com
          commit_message: Nuevo Push
          build_dir: build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
